// src/components/Sidebar.vue
<template>
  <div class="w-64 bg-white border-r border-gray-200 flex flex-col">
    <!-- Logo -->
    <div class="p-6 border-b border-gray-200">
      <div class="flex items-center space-x-2">
        <div class="w-8 h-8 bg-blue-600 rounded flex items-center justify-center">
          <span class="text-white font-bold text-sm">L</span>
        </div>
        <span class="font-semibold text-gray-900">Lano</span>
      </div>
    </div>


   <!-- User Profile Section at Bottom -->
   <div class="p-4 border-t border-gray-200">
     <div class="flex items-center space-x-3 p-3 rounded-lg hover:bg-gray-50 cursor-pointer">
       <div class="w-10 h-10 bg-gradient-to-r from-blue-500 to-purple-500 rounded-full flex items-center justify-center">
         <i class="fas fa-user text-white text-sm"></i>
       </div>
       <div class="flex-1 min-w-0">
         <p class="text-sm font-medium text-gray-900 truncate">Vipul Solanki</p>
         <p class="text-xs text-gray-500 truncate">Admin • Online</p>
       </div>
       <div class="flex items-center space-x-2">
         <div class="w-2 h-2 bg-green-400 rounded-full"></div>
         <i class="fas fa-chevron-up text-gray-400 text-xs"></i>
       </div>
     </div>
     
     <!-- Quick Actions -->
     <div class="mt-2 space-y-1">
       <button class="w-full flex items-center px-3 py-2 text-sm text-gray-600 rounded-md hover:bg-gray-100">
         <i class="fas fa-user-cog w-4 h-4 mr-3 text-gray-400"></i>
         Profile Settings
       </button>
       <button class="w-full flex items-center px-3 py-2 text-sm text-gray-600 rounded-md hover:bg-gray-100">
         <i class="fas fa-bell w-4 h-4 mr-3 text-gray-400"></i>
         Notifications
       </button>
       <button class="w-full flex items-center px-3 py-2 text-sm text-red-600 rounded-md hover:bg-red-50">
         <i class="fas fa-sign-out-alt w-4 h-4 mr-3 text-red-400"></i>
         Sign Out
       </button>
     </div>
   </div>
    <!-- Navigation -->
    <nav class="flex-1 p-4 space-y-1">
      <!-- Dashboard -->
      <div class="flex items-center px-3 py-2 text-sm font-medium text-gray-700 rounded-md hover:bg-gray-100">
        <i class="fas fa-chart-bar w-5 h-5 mr-3 text-gray-400"></i>
        Dashboard
      </div>

      <!-- Master Product Feed -->
      <div class="space-y-1">
        <div class="flex items-center justify-between px-3 py-2 text-sm font-medium text-gray-700 rounded-md hover:bg-gray-100">
          <div class="flex items-center">
            <i class="fas fa-box w-5 h-5 mr-3 text-gray-400"></i>
            Master Product Feed
          </div>
          <i class="fas fa-chevron-down w-3 h-3 text-gray-400"></i>
        </div>
      </div>

      <!-- Stores -->
      <div class="space-y-1">
        <div class="flex items-center justify-between px-3 py-2 text-sm font-medium text-gray-700 rounded-md hover:bg-gray-100">
          <div class="flex items-center">
            <i class="fas fa-store w-5 h-5 mr-3 text-gray-400"></i>
            Stores
          </div>
          <i class="fas fa-chevron-down w-3 h-3 text-gray-400"></i>
        </div>
        
        <!-- Lano Submenu -->
        <div class="ml-8 space-y-1">
          <div class="flex items-center justify-between px-3 py-2 text-sm font-medium text-gray-700 rounded-md hover:bg-gray-100">
            <span>Lano</span>
            <i class="fas fa-chevron-down w-3 h-3 text-gray-400"></i>
          </div>
          
          <!-- Sub-navigation -->
          <div class="ml-4 space-y-1">
            <div class="px-3 py-2 text-sm text-gray-600 rounded-md hover:bg-gray-100">Dashboard</div>
            <div class="px-3 py-2 text-sm text-blue-600 bg-blue-50 rounded-md font-medium">Product</div>
            <div class="px-3 py-2 text-sm text-gray-600 rounded-md hover:bg-gray-100">Category Master</div>
            <div class="px-3 py-2 text-sm text-gray-600 rounded-md hover:bg-gray-100">Category Order</div>
            <div class="px-3 py-2 text-sm text-gray-600 rounded-md hover:bg-gray-100">Product Order</div>
            <div class="px-3 py-2 text-sm text-gray-600 rounded-md hover:bg-gray-100">Brand Master</div>
            <div class="px-3 py-2 text-sm text-gray-600 rounded-md hover:bg-gray-100">Promotions Deal</div>
            <div class="px-3 py-2 text-sm text-gray-600 rounded-md hover:bg-gray-100">Career Page Forms</div>
            <div class="px-3 py-2 text-sm text-gray-600 rounded-md hover:bg-gray-100">Vendor Mapping</div>
          </div>
        </div>
      </div>

      <!-- Content Management -->
      <div class="flex items-center justify-between px-3 py-2 text-sm font-medium text-gray-700 rounded-md hover:bg-gray-100">
        <div class="flex items-center">
          <i class="fas fa-file-alt w-5 h-5 mr-3 text-gray-400"></i>
          Content Management
        </div>
        <i class="fas fa-chevron-down w-3 h-3 text-gray-400"></i>
      </div>

      <!-- Orders -->
      <div class="flex items-center justify-between px-3 py-2 text-sm font-medium text-gray-700 rounded-md hover:bg-gray-100">
        <div class="flex items-center">
          <i class="fas fa-shopping-cart w-5 h-5 mr-3 text-gray-400"></i>
          Orders
        </div>
        <i class="fas fa-chevron-down w-3 h-3 text-gray-400"></i>
      </div>

      <!-- Customer -->
      <div class="flex items-center justify-between px-3 py-2 text-sm font-medium text-gray-700 rounded-md hover:bg-gray-100">
        <div class="flex items-center">
          <i class="fas fa-users w-5 h-5 mr-3 text-gray-400"></i>
          Customer
        </div>
        <i class="fas fa-chevron-down w-3 h-3 text-gray-400"></i>
      </div>

      <!-- Promotions -->
      <div class="flex items-center justify-between px-3 py-2 text-sm font-medium text-gray-700 rounded-md hover:bg-gray-100">
        <div class="flex items-center">
          <i class="fas fa-tags w-5 h-5 mr-3 text-gray-400"></i>
          Promotions
        </div>
        <i class="fas fa-chevron-down w-3 h-3 text-gray-400"></i>
      </div>

      <!-- Settings -->
      <div class="flex items-center justify-between px-3 py-2 text-sm font-medium text-gray-700 rounded-md hover:bg-gray-100">
        <div class="flex items-center">
          <i class="fas fa-cog w-5 h-5 mr-3 text-gray-400"></i>
          Settings
        </div>
        <i class="fas fa-chevron-down w-3 h-3 text-gray-400"></i>
      </div>

      <!-- Configurator -->
      <div class="flex items-center px-3 py-2 text-sm font-medium text-gray-700 rounded-md hover:bg-gray-100">
        <i class="fas fa-wrench w-5 h-5 mr-3 text-gray-400"></i>
        Configurator
      </div>

      <!-- Reports -->
      <div class="flex items-center px-3 py-2 text-sm font-medium text-gray-700 rounded-md hover:bg-gray-100">
        <i class="fas fa-chart-line w-5 h-5 mr-3 text-gray-400"></i>
        Reports
      </div>
    </nav>
  </div>
</template>

<script>
export default {
  name: 'Sidebar'
}
</script>

// app/components/Sidebar.tsx
import { 
  HomeIcon, 
  CubeIcon, 
  BuildingStorefrontIcon,
  ClipboardDocumentListIcon,
  UserGroupIcon,
  TagIcon,
  Cog6ToothIcon,
  WrenchScrewdriverIcon,
  ChartBarIcon
} from '@heroicons/react/24/outline'
import { ChevronDownIcon, ChevronRightIcon } from '@heroicons/react/20/solid'
import { useState } from 'react'

const navigation = [
  { name: 'Dashboard', icon: HomeIcon, current: false },
  { 
    name: 'Master Product Feed', 
    icon: CubeIcon, 
    current: false,
    children: []
  },
  { 
    name: 'Stores', 
    icon: BuildingStorefrontIcon, 
    current: false,
    children: [
      { name: 'Lano', current: false, children: [
        { name: 'Dashboard', current: false },
        { name: 'Product', current: true },
        { name: 'Category Master', current: false },
        { name: 'Category Order', current: false },
        { name: 'Product Order', current: false },
        { name: 'Brand Master', current: false },
        { name: 'Promotions Deal', current: false },
        { name: 'Career Page Forms', current: false },
        { name: 'Vendor Mapping', current: false },
      ]}
    ]
  },
  { 
    name: 'Content Management', 
    icon: ClipboardDocumentListIcon, 
    current: false,
    children: []
  },
  { 
    name: 'Orders', 
    icon: ClipboardDocumentListIcon, 
    current: false,
    children: []
  },
  { 
    name: 'Customer', 
    icon: UserGroupIcon, 
    current: false,
    children: []
  },
  { 
    name: 'Promotions', 
    icon: TagIcon, 
    current: false,
    children: []
  },
  { 
    name: 'Settings', 
    icon: Cog6ToothIcon, 
    current: false,
    children: []
  },
  { 
    name: 'Configurator', 
    icon: WrenchScrewdriverIcon, 
    current: false,
    children: []
  },
  { 
    name: 'Reports', 
    icon: ChartBarIcon, 
    current: false,
    children: []
  },
]

function classNames(...classes: string[]) {
  return classes.filter(Boolean).join(' ')
}

export default function Sidebar() {
  const [expandedItems, setExpandedItems] = useState<string[]>(['Stores', 'Lano'])

  const toggleExpanded = (itemName: string) => {
    setExpandedItems(prev => 
      prev.includes(itemName) 
        ? prev.filter(name => name !== itemName)
        : [...prev, itemName]
    )
  }

  const renderNavItem = (item: any, level = 0) => {
    const isExpanded = expandedItems.includes(item.name)
    const hasChildren = item.children && item.children.length > 0

    return (
      <div key={item.name}>
        <div
          className={classNames(
            item.current
              ? 'bg-primary-50 border-r-2 border-primary-600 text-primary-700'
              : 'text-gray-700 hover:text-gray-900 hover:bg-gray-50',
            'group flex items-center px-2 py-2 text-sm font-medium cursor-pointer',
            level === 0 ? 'pl-3' : level === 1 ? 'pl-6' : 'pl-9'
          )}
          onClick={() => hasChildren && toggleExpanded(item.name)}
        >
          {level === 0 && item.icon && (
            <item.icon
              className={classNames(
                item.current ? 'text-primary-500' : 'text-gray-400 group-hover:text-gray-500',
                'mr-3 flex-shrink-0 h-5 w-5'
              )}
              aria-hidden="true"
            />
          )}
          <span className="flex-1">{item.name}</span>
          {hasChildren && (
            isExpanded ? (
              <ChevronDownIcon className="ml-2 h-4 w-4 text-gray-400" />
            ) : (
              <ChevronRightIcon className="ml-2 h-4 w-4 text-gray-400" />
            )
          )}
        </div>
        {hasChildren && isExpanded && (
          <div className="space-y-1">
            {item.children.map((child: any) => renderNavItem(child, level + 1))}
          </div>
        )}
      </div>
    )
  }

  return (
    <div className="flex flex-col w-64 bg-white border-r border-gray-200">
      {/* Logo */}
      <div className="flex items-center h-16 px-4 border-b border-gray-200">
        <div className="flex items-center">
          <div className="w-8 h-8 bg-primary-600 rounded-lg flex items-center justify-center">
            <span className="text-white font-bold text-sm">L</span>
          </div>
          <span className="ml-2 text-xl font-semibold text-gray-900">lano</span>
        </div>
      </div>

      {/* Navigation */}
      <nav className="flex-1 px-2 py-4 space-y-1 overflow-y-auto">
        {navigation.map((item) => renderNavItem(item))}
      </nav>
    </div>
  )
}
