// src/App.vue
<template>
  <div class="flex h-screen bg-gray-50">
    <!-- Left Sidebar -->
    <Sidebar />
    
    <!-- Main Content -->
    <div class="flex-1 flex flex-col overflow-hidden">
      <!-- Top Header -->
      <TopHeader />
      
      <!-- Products Content -->
      <ProductsPage />
    </div>
  </div>
</template>

<script>
import Sidebar from './components/Sidebar.vue'
import TopHeader from './components/TopHeader.vue'
import ProductsPage from './components/ProductsPage.vue'

export default {
  name: 'App',
  components: {
    Sidebar,
    TopHeader,
    ProductsPage
  }
}
</script>

// app/page.tsx
import Sidebar from './components/Sidebar'
import Header from './components/Header'
import ProductTable from './components/ProductTable'

export default function Home() {
  return (
    <div className="flex h-screen bg-gray-25">
      <Sidebar />
      <div className="flex-1 flex flex-col overflow-hidden">
        <Header />
        <main className="flex-1 overflow-x-hidden overflow-y-auto bg-gray-25">
          <div className="container mx-auto px-6 py-8">
            <ProductTable />
          </div>
        </main>
      </div>
    </div>
  )
}
